version: "3"
services:
    base:
        # build: /Users/tibor/2-Areas/Dev/docker/tbrlpld/ubuntu/
        image: tbrlpld/ubuntu:latest
    frontend:
        build: ./movieservice-frontend/
        image: movieservice/frontend:latest
        depends_on:
            - base
            - backend
        ports: 
            - "127.0.0.1:80:8080"
    backend:
        build: ./movieservice-backend/
        image: movieservice/backend:latest
        command: /venv/bin/python app.py 1> app.log 2> app.err
        depends_on:
            - base
        ports: 
            - "127.0.0.1:7007:7007"
        volumes:
            - ./movieservice-backend/src/:/app
