"""Add other float column to bill

Revision ID: 4c9a9200c1b9
Revises: 4e6910bdc69b
Create Date: 2019-12-17 16:22:52.628136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9a9200c1b9'
down_revision = '4e6910bdc69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('other', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'other')
    # ### end Alembic commands ###
