"""Add last_payment_date column to bill

Revision ID: 4e6910bdc69b
Revises: 
Create Date: 2019-12-17 16:18:20.116155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6910bdc69b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('last_payment_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bills_last_payment_date'), 'bills', ['last_payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_last_payment_date'), table_name='bills')
    op.drop_column('bills', 'last_payment_date')
    # ### end Alembic commands ###
