dummy_movies = {
  "keyword": "top_10",
  "hits": [
    {
      "imdb_code": "tt0691996",
      "title": "Towering Inferno",
      "director": "John Blanchard",
      "keywords": [],
      "duration": 65,
      "genres": [
        "comedy",
      ],
      "rating": "",
      "year": 0,
      "imdb_score": 9.5,
    },
    {
      "imdb_code": "tt0111161",
      "title": "The Shawshank Redemption",
      "director": "Frank Darabont",
      "keywords": [
        "first person narration",
        "prison",
        "wrongful imprisonment",
        "prison cell search",
        "escape from prison",,
      ],
      "duration": 142,
      "genres": [
        "crime",
        "drama",,
      ],
      "rating": "R",
      "year": 1994,
      "imdb_score": 9.3,,
    },
    {
      "imdb_code": "tt0068646",
      "title": "The Godfather",
      "director": "Francis Ford Coppola",
      "keywords": [
        "organized crime",
        "rise to power",
        "crime family",
        "patriarch",
        "mafia",,
      ],
      "duration": 175,
      "genres": [
        "crime",
        "drama",,
      ],
      "rating": "R",
      "year": 1972,
      "imdb_score": 9.2,,
    },
    {
      "imdb_code": "tt0092337",
      "title": "Dekalog",
      "director": "",
      "keywords": [
        "search for meaning",
        "moral challenge",
        "meaning of life",
        "morality",
        "ten commandments",,
      ],
      "duration": 55,
      "genres": [
        "drama",,
      ],
      "rating": "TV-MA",
      "year": 0,
      "imdb_score": 9.1,
    },
    {
      "imdb_code": "tt3082898",
      "title": "Kickboxer: Vengeance",
      "director": "John Stockwell",
      "keywords": [],
      "duration": 90,
      "genres": [
        "action",
      ],
      "rating": "",
      "year": 2016,
      "imdb_score": 9.1,
    },
    {
      "imdb_code": "tt0468569",
      "title": "The Dark Knight",
      "director": "Christopher Nolan",
      "keywords": [
        "based on comic book",
        "star died before release",
        "dc comics",
        "urban setting",
        "psychopath",
      ],
      "duration": 152,
      "genres": [
        "crime",
        "action",
        "drama",
        "thriller",
      ],
      "rating": "PG-13",
      "year": 2008,
      "imdb_score": 9.0,
    },
    {
      "imdb_code": "tt0071562",
      "title": "The Godfather: Part II",
      "director": "Francis Ford Coppola",
      "keywords": [
        "1950s",
        "corrupt politician",
        "melancholy",
        "revenge",
        "lake tahoe nevada",
      ],
      "duration": 220,
      "genres": [
        "crime",
        "drama",,
      ],
      "rating": "R",
      "year": 1974,
      "imdb_score": 9.0,,
    },
    {
      "imdb_code": "tt2802850",
      "title": "Fargo",
      "director": "",
      "keywords": [
        "anthology",
        "minnesota",
        "death",
        "insurance salesman",
        "police officer",,
      ],
      "duration": 53,
      "genres": [
        "crime",
        "drama",
        "thriller",,
      ],
      "rating": "TV-MA",
      "year": 0,
      "imdb_score": 9.0,,
    },
    {
      "imdb_code": "tt0167260",
      "title": "The Lord of the Rings: The Return of the King",
      "director": "Peter Jackson",
      "keywords": [
        "ring",
        "battle",
        "orc",
        "king",
        "epic",,
      ],
      "duration": 192,
      "genres": [
        "adventure",
        "action",
        "drama",
        "fantasy",,
      ],
      "rating": "PG-13",
      "year": 2003,
      "imdb_score": 8.9,,
    },
    {
      "imdb_code": "tt0108052",
      "title": "Schindler's List",
      "director": "Steven Spielberg",
      "keywords": [
        "jewish",
        "german soldier",
        "jew",
        "german",
        "nazi",,
      ],
      "duration": 185,
      "genres": [
        "biography",
        "drama",
        "history",,
      ],
      "rating": "R",
      "year": 1993,
      "imdb_score": 8.9,,
    },
  ],
  "truncated_results": true,
};

dummy_genres = [
  "action",
  "adventure",
  "animation",
  "biography",
  "comedy",
  "crime",
  "documentary",
  "drama",
  "family",
  "fantasy",
  "film-noir",
  "game-show",
  "history",
  "horror",
  "music",
  "musical",
  "mystery",
  "news",
  "reality-tv",
  "romance",
  "sci-fi",
  "short",
  "sport",
  "thriller",
  "war",
  "western"
]
