"""Add zipcode to location

Revision ID: 85a181348d85
Revises: 
Create Date: 2019-12-17 16:54:06.245195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a181348d85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('zipcode', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_locations_zipcode'), 'locations', ['zipcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_zipcode'), table_name='locations')
    op.drop_column('locations', 'zipcode')
    # ### end Alembic commands ###
