"""Added account model

Revision ID: 8a92caf8b5d3
Revises: 43a25a9ab678
Create Date: 2019-11-24 17:52:55.932713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a92caf8b5d3'
down_revision = '43a25a9ab678'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_records_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records'))
    )
    op.create_index(op.f('ix_records_category'), 'records', ['category'], unique=False)
    op.create_index(op.f('ix_records_type'), 'records', ['type'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_type'), table_name='records')
    op.drop_index(op.f('ix_records_category'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
